import {
  Worker,
  CustomerRecord,
  CatalogService,
  Booking,
  CoopStats,
  DemandForecast,
  NotificationItem,
  WorkerWelfare,
} from './types'

export const categories = [
  'Plumber',
  'Electrician',
  'Carpenter',
  'Painter',
  'Cleaner',
  'Gardener',
  'Driver',
  'Appliance Repair',
  'AC Technician',
  'Caregiver',
]

/**
 * 38 Realistic Gig Workers spanning all 10 trades, realistic Bengaluru geo-distribution,
 * verified/unverified statuses, varied workloads, and male/female cooperative members.
 */
export const initialWorkers: Worker[] = [
  // --- PLUMBING (5 Workers) ---
  {
    id: 101,
    name: 'Ramesh Verma',
    initials: 'RV',
    phone: '+91 98451 22345',
    service: 'Plumber',
    primarySkill: 'Plumber',
    secondarySkills: ['Pipe Fitting', 'Water Heater Repair'],
    experience: 9,
    certifications: ['Govt. ITI Plumbing Specialist', 'ISO Water Safety'],
    rating: 4.8,
    reviews: 142,
    completedJobs: 318,
    availability: 'Available',
    currentStatus: 'Available',
    price: 380,
    hourlyRate: 380,
    color: 'blue',
    bio: 'Certified master plumber for pipe leaks, bathroom fixtures, and pressure testing. Co-op member since 2023.',
    lat: 12.9795,
    lng: 77.601, // ~1.2 km from demo center [12.9716, 77.5946]
    serviceArea: 'Indiranagar & Central Bengaluru',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Bengaluru Kaushalya Sahakari',
    language: ['Kannada', 'Hindi', 'English'],
    workload: 1,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Austin Town, Bengaluru',
  },
  {
    id: 102,
    name: 'Amit Saxena',
    initials: 'AS',
    phone: '+91 98452 33456',
    service: 'Plumber',
    primarySkill: 'Plumber',
    secondarySkills: ['Drain Unblocking', 'Sanitary Fitting'],
    experience: 5,
    certifications: ['Skill India Certified Plumber'],
    rating: 4.7,
    reviews: 88,
    completedJobs: 174,
    availability: 'Available',
    currentStatus: 'Available',
    price: 350,
    hourlyRate: 350,
    color: 'mint',
    bio: 'Prompt emergency plumbing, drain unblocking, and water heater repairs. Transparent flat quotes.',
    lat: 12.956,
    lng: 77.609, // ~2.4 km from demo center
    serviceArea: 'Shanthi Nagar & Richmond',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Bengaluru Kaushalya Sahakari',
    language: ['Hindi', 'English'],
    workload: 2,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Shanthi Nagar, Bengaluru',
  },
  {
    id: 103,
    name: 'Suresh Nair',
    initials: 'SN',
    phone: '+91 98453 44567',
    service: 'Plumber',
    primarySkill: 'Plumber',
    secondarySkills: ['Pipeline Rerouting', 'Pump Overhaul'],
    experience: 12,
    certifications: ['Advanced Commercial Piping', 'Plumbing Supervisor Level 4'],
    rating: 4.9,
    reviews: 230,
    completedJobs: 512,
    availability: 'Busy', // Closer (0.8 km) but Busy!
    currentStatus: 'Busy',
    price: 450,
    hourlyRate: 450,
    color: 'peach',
    bio: '12 years specialized commercial and home plumbing. Currently handling an active apartment pipeline repair.',
    lat: 12.9765,
    lng: 77.599, // ~0.8 km from demo center
    serviceArea: 'Richmond Town & Brigade Rd',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Bengaluru Kaushalya Sahakari',
    language: ['Malayalam', 'English', 'Tamil'],
    workload: 4,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Richmond Town, Bengaluru',
  },
  {
    id: 104,
    name: 'Rekha Devi',
    initials: 'RD',
    phone: '+91 98454 55678',
    service: 'Plumber',
    primarySkill: 'Plumber',
    secondarySkills: ['RO Water Purifier', 'Leak Detection'],
    experience: 6,
    certifications: ['Jal Seva Plumbing Associate'],
    rating: 4.75,
    reviews: 94,
    completedJobs: 198,
    availability: 'Available',
    currentStatus: 'Available',
    price: 360,
    hourlyRate: 360,
    color: 'lilac',
    bio: 'Specialist in kitchen sink plumbing, water filters, and bathroom fixture replacement.',
    lat: 12.969,
    lng: 77.615, // ~2.2 km
    serviceArea: 'Domlur & Old Airport Rd',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Bengaluru Kaushalya Sahakari',
    language: ['Kannada', 'Hindi'],
    workload: 1,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Domlur, Bengaluru',
  },
  {
    id: 105,
    name: 'Manoj Tiwari',
    initials: 'MT',
    phone: '+91 98455 66789',
    service: 'Plumber',
    primarySkill: 'Plumber',
    secondarySkills: ['Overhead Tank Cleaning', 'Valve Replacement'],
    experience: 8,
    certifications: ['Plumbing Safety Tier 2'],
    rating: 4.6,
    reviews: 67,
    completedJobs: 145,
    availability: 'On Leave',
    currentStatus: 'On Leave',
    price: 390,
    hourlyRate: 390,
    color: 'yellow',
    bio: 'Water line installations and motor pump connections. Currently on scheduled weekly leave.',
    lat: 12.985,
    lng: 77.58, // ~2.1 km
    serviceArea: 'Malleshwaram & Seshadripuram',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Bengaluru Kaushalya Sahakari',
    language: ['Hindi', 'Bhojpuri'],
    workload: 0,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Seshadripuram, Bengaluru',
  },

  // --- ELECTRICAL (5 Workers) ---
  {
    id: 1,
    name: 'Rajesh Kumar',
    initials: 'RK',
    phone: '+91 98450 11223',
    service: 'Electrician',
    primarySkill: 'Electrician',
    secondarySkills: ['Inverter Repair', 'MCB Diagnostics', 'Smart Lighting'],
    experience: 8,
    certifications: ['Licensed Wireman Grade 1', 'Schneider Electric Certified'],
    rating: 4.8,
    reviews: 126,
    completedJobs: 285,
    availability: 'Available',
    currentStatus: 'Available',
    price: 450,
    hourlyRate: 450,
    color: 'peach',
    bio: 'Residential wiring, lighting and safety checks. Known for clear quotes and careful work.',
    lat: 12.978,
    lng: 77.604, // ~1.3 km
    serviceArea: 'Victoria Layout & MG Road',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Bengaluru Kaushalya Sahakari',
    language: ['Kannada', 'Hindi', 'English'],
    workload: 1,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Victoria Layout, Bengaluru',
  },
  {
    id: 106,
    name: 'Dinesh Bhat',
    initials: 'DB',
    phone: '+91 98456 77890',
    service: 'Electrician',
    primarySkill: 'Electrician',
    secondarySkills: ['Industrial Wiring', 'Solar Panel Servicing'],
    experience: 10,
    certifications: ['Master Electrician Board Certified'],
    rating: 4.9,
    reviews: 180,
    completedJobs: 410,
    availability: 'Busy', // Closer (0.7 km) but Busy!
    currentStatus: 'Busy',
    price: 500,
    hourlyRate: 500,
    color: 'yellow',
    bio: 'Industrial and home electrical safety inspector. Currently on a scheduled panel upgrade.',
    lat: 12.975,
    lng: 77.598, // ~0.7 km
    serviceArea: 'Langford Town & Ashok Nagar',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Bengaluru Kaushalya Sahakari',
    language: ['Kannada', 'English'],
    workload: 3,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Langford Town, Bengaluru',
  },
  {
    id: 9,
    name: 'Kiran Rao',
    initials: 'KR',
    phone: '+91 98457 88901',
    service: 'Electrician',
    primarySkill: 'Electrician',
    secondarySkills: ['Ceiling Fan Setup', 'Switchboard Repair'],
    experience: 4,
    certifications: ['ITI Electrical Apprentice'],
    rating: 4.4,
    reviews: 41,
    completedJobs: 92,
    availability: 'Available',
    currentStatus: 'Available',
    price: 400,
    hourlyRate: 400,
    color: 'lilac',
    bio: 'Friendly electrical support for homes and small businesses.',
    lat: 12.99,
    lng: 77.63, // ~4.3 km
    serviceArea: 'Ulsoor & Indiranagar',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Bengaluru Kaushalya Sahakari',
    language: ['Kannada', 'Telugu'],
    workload: 2,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Ulsoor, Bengaluru',
  },
  {
    id: 107,
    name: 'Sunita Sharma',
    initials: 'SS',
    phone: '+91 98458 99012',
    service: 'Electrician',
    primarySkill: 'Electrician',
    secondarySkills: ['LED Strip Installation', 'Appliance Earthing'],
    experience: 6,
    certifications: ['State Electrical Safety License'],
    rating: 4.85,
    reviews: 110,
    completedJobs: 235,
    availability: 'Available',
    currentStatus: 'Available',
    price: 440,
    hourlyRate: 440,
    color: 'mint',
    bio: 'Precise circuit breaker troubleshooting, kitchen appliance wiring, and child-safe outlets.',
    lat: 12.962,
    lng: 77.595, // ~1.1 km
    serviceArea: 'Wilson Garden & Shanthi Nagar',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Bengaluru Kaushalya Sahakari',
    language: ['Hindi', 'English'],
    workload: 1,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Wilson Garden, Bengaluru',
  },
  {
    id: 108,
    name: 'Abdul Hameed',
    initials: 'AH',
    phone: '+91 98459 00123',
    service: 'Electrician',
    primarySkill: 'Electrician',
    secondarySkills: ['Heavy Generator Hookup', 'Stabilizer Repair'],
    experience: 11,
    certifications: ['High Voltage Safety Certified'],
    rating: 4.7,
    reviews: 135,
    completedJobs: 340,
    availability: 'Offline',
    currentStatus: 'Offline',
    price: 480,
    hourlyRate: 480,
    color: 'blue',
    bio: 'Emergency short-circuit diagnosis and heavy power load management.',
    lat: 12.94,
    lng: 77.585, // ~3.7 km
    serviceArea: 'Jayanagar & Basavanagudi',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Bengaluru Kaushalya Sahakari',
    language: ['Urdu', 'Kannada', 'Hindi'],
    workload: 0,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Jayanagar, Bengaluru',
  },

  // --- CLEANING (5 Workers) ---
  {
    id: 4,
    name: 'Priya Sharma',
    initials: 'PS',
    phone: '+91 98460 11234',
    service: 'Cleaner',
    primarySkill: 'Cleaner',
    secondarySkills: ['Deep Sanitation', 'Eco-friendly Supplies', 'Sofa Shampooing'],
    experience: 5,
    certifications: ['Professional Hygiene Certified', 'Green Clean Accredited'],
    rating: 4.9,
    reviews: 211,
    completedJobs: 480,
    availability: 'Available',
    currentStatus: 'Available',
    price: 400,
    hourlyRate: 400,
    color: 'mint',
    bio: 'Detail-focused home cleaner who brings her own eco-friendly supplies and specialized tools.',
    lat: 12.975,
    lng: 77.589, // ~0.8 km
    serviceArea: 'Ashok Nagar & Lavelle Rd',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Mahila Shramik Sahakari',
    language: ['Hindi', 'English'],
    workload: 1,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Ashok Nagar, Bengaluru',
  },
  {
    id: 10,
    name: 'Fatima Ali',
    initials: 'FA',
    phone: '+91 98461 22345',
    service: 'Cleaner',
    primarySkill: 'Cleaner',
    secondarySkills: ['Move-out Deep Clean', 'Kitchen De-greasing'],
    experience: 8,
    certifications: ['Commercial Sanitization Level 3'],
    rating: 4.8,
    reviews: 109,
    completedJobs: 290,
    availability: 'Busy',
    currentStatus: 'Busy',
    price: 450,
    hourlyRate: 450,
    color: 'yellow',
    bio: 'Trusted weekly and move-out cleaning specialist.',
    lat: 12.945,
    lng: 77.61, // ~3.5 km
    serviceArea: 'Adugodi & Koramangala',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Mahila Shramik Sahakari',
    language: ['Hindi', 'Urdu', 'Kannada'],
    workload: 3,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Adugodi, Bengaluru',
  },
  {
    id: 109,
    name: 'Anita Desai',
    initials: 'AD',
    phone: '+91 98462 33456',
    service: 'Cleaner',
    primarySkill: 'Cleaner',
    secondarySkills: ['Window Polishing', 'Balcony Pressure Wash'],
    experience: 6,
    certifications: ['Certified Residential Housekeeper'],
    rating: 4.8,
    reviews: 95,
    completedJobs: 215,
    availability: 'Available',
    currentStatus: 'Available',
    price: 390,
    hourlyRate: 390,
    color: 'peach',
    bio: 'Thorough bathroom and kitchen sanitization with hospital-grade disinfectant.',
    lat: 12.968,
    lng: 77.602, // ~0.9 km
    serviceArea: 'Richmond Town & Langford',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Mahila Shramik Sahakari',
    language: ['Marathi', 'Hindi', 'Kannada'],
    workload: 2,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Richmond Town, Bengaluru',
  },
  {
    id: 110,
    name: 'Lakshmi Narayanan',
    initials: 'LN',
    phone: '+91 98463 44567',
    service: 'Cleaner',
    primarySkill: 'Cleaner',
    secondarySkills: ['Post-renovation Cleanup', 'Carpet Steaming'],
    experience: 7,
    certifications: ['Steam Sanitation Expert'],
    rating: 4.75,
    reviews: 82,
    completedJobs: 178,
    availability: 'Available',
    currentStatus: 'Available',
    price: 420,
    hourlyRate: 420,
    color: 'blue',
    bio: 'Specialist in post-renovation dust elimination and tiled floor restoration.',
    lat: 12.983,
    lng: 77.61, // ~1.9 km
    serviceArea: 'Halasuru & Cox Town',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Mahila Shramik Sahakari',
    language: ['Tamil', 'Kannada', 'English'],
    workload: 1,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Halasuru, Bengaluru',
  },

  // --- CARPENTRY (4 Workers) ---
  {
    id: 111,
    name: 'Vijay Patil',
    initials: 'VP',
    phone: '+91 98464 55678',
    service: 'Carpenter',
    primarySkill: 'Carpenter',
    secondarySkills: ['Modular Furniture', 'Lock Replacement', 'Modular Kitchen'],
    experience: 7,
    certifications: ['Woodworking Guild Guildmaster Cert'],
    rating: 4.8,
    reviews: 112,
    completedJobs: 240,
    availability: 'Available',
    currentStatus: 'Available',
    price: 520,
    hourlyRate: 520,
    color: 'blue',
    bio: 'Door hinge fixes, bespoke shelving, modular cabinet assembly, and wood restoration.',
    lat: 12.968,
    lng: 77.608, // ~1.5 km
    serviceArea: 'Viveka Nagar & Domlur',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Bengaluru Kaushalya Sahakari',
    language: ['Kannada', 'Hindi'],
    workload: 1,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Viveka Nagar, Bengaluru',
  },
  {
    id: 3,
    name: 'Sunil Verma',
    initials: 'SV',
    phone: '+91 98465 66789',
    service: 'Carpenter',
    primarySkill: 'Carpenter',
    secondarySkills: ['Antique Wood Polish', 'Custom Wardrobes'],
    experience: 11,
    certifications: ['Master Craftsman Carpentry'],
    rating: 4.6,
    reviews: 84,
    completedJobs: 220,
    availability: 'Busy',
    currentStatus: 'Busy',
    price: 600,
    hourlyRate: 600,
    color: 'lilac',
    bio: 'Custom furniture, repairs and installations. 11 years serving the neighborhood.',
    lat: 12.95,
    lng: 77.62, // ~3.6 km
    serviceArea: 'Koramangala & HSR',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Bengaluru Kaushalya Sahakari',
    language: ['Hindi', 'Punjabi'],
    workload: 4,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Koramangala, Bengaluru',
  },
  {
    id: 112,
    name: 'Gurpreet Singh',
    initials: 'GS',
    phone: '+91 98466 77890',
    service: 'Carpenter',
    primarySkill: 'Carpenter',
    secondarySkills: ['Bed Frame Assembly', 'Sliding Door Track'],
    experience: 9,
    certifications: ['IKEA Furniture Assembly Expert'],
    rating: 4.88,
    reviews: 130,
    completedJobs: 295,
    availability: 'Available',
    currentStatus: 'Available',
    price: 540,
    hourlyRate: 540,
    color: 'peach',
    bio: 'Flat-pack furniture assembly and sturdy balcony wooden deck fixtures.',
    lat: 12.973,
    lng: 77.615, // ~2.1 km
    serviceArea: 'Indiranagar & Cambridge Layout',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Bengaluru Kaushalya Sahakari',
    language: ['Punjabi', 'Hindi', 'English'],
    workload: 1,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Cambridge Layout, Bengaluru',
  },

  // --- PAINTING (4 Workers) ---
  {
    id: 5,
    name: 'Arjun Patel',
    initials: 'AP',
    phone: '+91 98467 88901',
    service: 'Painter',
    primarySkill: 'Painter',
    secondarySkills: ['Waterproofing', 'Texture Wall Design'],
    experience: 7,
    certifications: ['Asian Paints Master Painter'],
    rating: 4.5,
    reviews: 73,
    completedJobs: 160,
    availability: 'Available',
    currentStatus: 'Available',
    price: 700,
    hourlyRate: 700,
    color: 'yellow',
    bio: 'Interior touch-ups and full-room painting with neat, reliable finishes.',
    lat: 12.964,
    lng: 77.585, // ~1.5 km
    serviceArea: 'Sampangi Rama Nagar & Central',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Bengaluru Kaushalya Sahakari',
    language: ['Gujarati', 'Hindi', 'English'],
    workload: 2,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Sampangi Rama Nagar, Bengaluru',
  },
  {
    id: 113,
    name: 'Manpreet Kaur',
    initials: 'MK',
    phone: '+91 98468 99012',
    service: 'Painter',
    primarySkill: 'Painter',
    secondarySkills: ['Stenciling', 'Door Enamel Polish'],
    experience: 6,
    certifications: ['Dulux Certified Colour Consultant'],
    rating: 4.7,
    reviews: 68,
    completedJobs: 142,
    availability: 'Available',
    currentStatus: 'Available',
    price: 650,
    hourlyRate: 650,
    color: 'mint',
    bio: 'Accent walls, fine lacquer finishes, and odor-free zero-VOC residential coatings.',
    lat: 12.982,
    lng: 77.605, // ~1.6 km
    serviceArea: 'Shivaji Nagar & Ulsoor',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Bengaluru Kaushalya Sahakari',
    language: ['Hindi', 'Punjabi', 'English'],
    workload: 1,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Shivaji Nagar, Bengaluru',
  },

  // --- AC & HVAC TECHNICIAN (4 Workers) ---
  {
    id: 114,
    name: 'Farhan Akhtar',
    initials: 'FA',
    phone: '+91 98469 00123',
    service: 'AC Technician',
    primarySkill: 'AC Technician',
    secondarySkills: ['Split AC Gas Refill', 'Compressor Overhaul', 'Duct Cleaning'],
    experience: 8,
    certifications: ['Daikin Certified AC Engineer', 'R-32 Refrigerant Certified'],
    rating: 4.88,
    reviews: 145,
    completedJobs: 330,
    availability: 'Available',
    currentStatus: 'Available',
    price: 499,
    hourlyRate: 499,
    color: 'blue',
    bio: 'Split & window AC deep jet cleaning, eco-friendly gas recharging, and cooling troubleshooting.',
    lat: 12.973,
    lng: 77.602, // ~0.8 km
    serviceArea: 'Central Bengaluru & Indiranagar',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Bengaluru Kaushalya Sahakari',
    language: ['Urdu', 'Hindi', 'English'],
    workload: 1,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Residency Rd, Bengaluru',
  },
  {
    id: 115,
    name: 'Naveen Chander',
    initials: 'NC',
    phone: '+91 98470 11234',
    service: 'AC Technician',
    primarySkill: 'AC Technician',
    secondarySkills: ['Inverter AC PCB Board', 'Copper Piping'],
    experience: 6,
    certifications: ['Voltas Authorized Partner'],
    rating: 4.75,
    reviews: 89,
    completedJobs: 195,
    availability: 'Busy',
    currentStatus: 'Busy',
    price: 520,
    hourlyRate: 520,
    color: 'peach',
    bio: 'Expert inverter board diagnostic technician. Currently completing a multi-unit office service.',
    lat: 12.966,
    lng: 77.592, // ~0.8 km
    serviceArea: 'Richmond Town & Shanthi Nagar',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Bengaluru Kaushalya Sahakari',
    language: ['Telugu', 'English'],
    workload: 3,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Shanthi Nagar, Bengaluru',
  },

  // --- APPLIANCE REPAIR (4 Workers) ---
  {
    id: 8,
    name: 'Neha Gupta',
    initials: 'NG',
    phone: '+91 98471 22345',
    service: 'Appliance Repair',
    primarySkill: 'Appliance Repair',
    secondarySkills: ['Washing Machine', 'Refrigerator', 'Microwave Diagnostic'],
    experience: 7,
    certifications: ['LG & Whirlpool Authorized Appliance Specialist'],
    rating: 4.8,
    reviews: 117,
    completedJobs: 260,
    availability: 'Available',
    currentStatus: 'Available',
    price: 300,
    hourlyRate: 300,
    color: 'peach',
    bio: 'Washing machine, refrigerator and small appliance diagnostics. Same-day genuine spare parts.',
    lat: 12.965,
    lng: 77.59, // ~1.0 km
    serviceArea: 'Langford Gardens & Central',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Bengaluru Kaushalya Sahakari',
    language: ['Hindi', 'English'],
    workload: 1,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Langford Gardens, Bengaluru',
  },
  {
    id: 116,
    name: 'Satish Kumar',
    initials: 'SK',
    phone: '+91 98472 33456',
    service: 'Appliance Repair',
    primarySkill: 'Appliance Repair',
    secondarySkills: ['Water Heater Geyser', 'Kitchen Chimney Service'],
    experience: 9,
    certifications: ['Samsung Technical Partner'],
    rating: 4.7,
    reviews: 98,
    completedJobs: 215,
    availability: 'Available',
    currentStatus: 'Available',
    price: 320,
    hourlyRate: 320,
    color: 'mint',
    bio: 'Fast geyser element replacement, microwave oven magnetron checks, and chimney motor cleaning.',
    lat: 12.978,
    lng: 77.61, // ~1.8 km
    serviceArea: 'Halasuru & Indiranagar',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Bengaluru Kaushalya Sahakari',
    language: ['Kannada', 'Tamil'],
    workload: 2,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Halasuru, Bengaluru',
  },

  // --- CAREGIVER (4 Workers) ---
  {
    id: 117,
    name: 'Meenakshi Sundaram',
    initials: 'MS',
    phone: '+91 98473 44567',
    service: 'Caregiver',
    primarySkill: 'Caregiver',
    secondarySkills: ['Elderly Mobility', 'Medication Management', 'Post-Op Care'],
    experience: 8,
    certifications: ['Certified Geriatric Caregiver', 'Red Cross First Aid & CPR'],
    rating: 4.95,
    reviews: 140,
    completedJobs: 280,
    availability: 'Available',
    currentStatus: 'Available',
    price: 550,
    hourlyRate: 550,
    color: 'mint',
    bio: 'Compassionate, experienced elderly companion and patient care nurse. Verified medical background.',
    lat: 12.974,
    lng: 77.599, // ~0.5 km
    serviceArea: 'Central Bengaluru & Richmond',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Sanjeevani Seva Sahakari',
    language: ['Tamil', 'Kannada', 'English'],
    workload: 1,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Richmond Circle, Bengaluru',
  },
  {
    id: 118,
    name: 'Pushpa Devi',
    initials: 'PD',
    phone: '+91 98474 55678',
    service: 'Caregiver',
    primarySkill: 'Caregiver',
    secondarySkills: ['Physiotherapy Assistant', 'Dietary Meal Prep'],
    experience: 6,
    certifications: ['Home Healthcare Diploma'],
    rating: 4.82,
    reviews: 86,
    completedJobs: 175,
    availability: 'Available',
    currentStatus: 'Available',
    price: 500,
    hourlyRate: 500,
    color: 'peach',
    bio: 'Patient recovery support, blood pressure monitoring, gentle walking assistance and nutrition.',
    lat: 12.961,
    lng: 77.605, // ~1.6 km
    serviceArea: 'Langford & Shanthi Nagar',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Sanjeevani Seva Sahakari',
    language: ['Hindi', 'Bhojpuri'],
    workload: 1,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Langford Town, Bengaluru',
  },

  // --- GARDENING (4 Workers) ---
  {
    id: 119,
    name: 'Prakash Rao',
    initials: 'PR',
    phone: '+91 98475 66789',
    service: 'Gardener',
    primarySkill: 'Gardener',
    secondarySkills: ['Terrace Gardening', 'Bonsai Pruning', 'Organic Fertilizers'],
    experience: 8,
    certifications: ['Horticulture Board Master Gardener'],
    rating: 4.8,
    reviews: 94,
    completedJobs: 210,
    availability: 'Available',
    currentStatus: 'Available',
    price: 480,
    hourlyRate: 480,
    color: 'mint',
    bio: 'Organic terrace gardening, lawn mowing, seasonal planting, and pest-safe maintenance.',
    lat: 12.969,
    lng: 77.602, // ~0.9 km
    serviceArea: 'Domlur & Indiranagar',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Bengaluru Kaushalya Sahakari',
    language: ['Kannada', 'Telugu'],
    workload: 1,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Domlur, Bengaluru',
  },
  {
    id: 6,
    name: 'Mohan Yadav',
    initials: 'MY',
    phone: '+91 98476 77890',
    service: 'Gardener',
    primarySkill: 'Gardener',
    secondarySkills: ['Lawn Care', 'Balcony Makeovers'],
    experience: 9,
    certifications: ['Landscape Care Associate'],
    rating: 4.7,
    reviews: 65,
    completedJobs: 150,
    availability: 'Offline',
    currentStatus: 'Offline',
    price: 500,
    hourlyRate: 500,
    color: 'green',
    bio: 'Garden care, pruning and balcony makeovers for busy households.',
    lat: 12.96,
    lng: 77.64, // ~5.1 km
    serviceArea: 'HAL 2nd Stage & Indiranagar',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Bengaluru Kaushalya Sahakari',
    language: ['Hindi', 'Kannada'],
    workload: 0,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'HAL 2nd Stage, Bengaluru',
  },

  // --- DRIVER (4 Workers) ---
  {
    id: 7,
    name: 'Ravi Singh',
    initials: 'RS',
    phone: '+91 98477 88901',
    service: 'Driver',
    primarySkill: 'Driver',
    secondarySkills: ['Outstation Trips', 'Airport Express', 'Luxury Sedans'],
    experience: 10,
    certifications: ['Commercial Driving License (Heavy & Light)', 'Defensive Driving Certified'],
    rating: 4.6,
    reviews: 154,
    completedJobs: 390,
    availability: 'Available',
    currentStatus: 'Available',
    price: 550,
    hourlyRate: 550,
    color: 'blue',
    bio: 'Verified local driver for errands, airport runs and family transport. 10 years clean record.',
    lat: 12.98,
    lng: 77.618, // ~2.7 km
    serviceArea: 'Halasuru & Indiranagar',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Sarathi Sahakari Transport',
    language: ['Hindi', 'Kannada', 'English'],
    workload: 2,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Halasuru, Bengaluru',
  },
  {
    id: 120,
    name: 'Sumit Hegde',
    initials: 'SH',
    phone: '+91 98478 99012',
    service: 'Driver',
    primarySkill: 'Driver',
    secondarySkills: ['Automatic & Manual Cars', 'City Errand Specialist'],
    experience: 7,
    certifications: ['Commercial Badge Verified', 'First Responder Certified'],
    rating: 4.85,
    reviews: 120,
    completedJobs: 280,
    availability: 'Available',
    currentStatus: 'Available',
    price: 520,
    hourlyRate: 520,
    color: 'peach',
    bio: 'Punctual, polite chauffeur for city hospital visits, office commutes, and weekend travel.',
    lat: 12.971,
    lng: 77.591, // ~0.4 km
    serviceArea: 'MG Road, Lavelle & Ashok Nagar',
    verified: true,
    verificationStatus: 'Verified',
    cooperative: 'Sarathi Sahakari Transport',
    language: ['Kannada', 'Konkani', 'English'],
    workload: 1,
    insuranceStatus: 'Active (₹5,00,000 Group Cover)',
    address: 'Lavelle Road, Bengaluru',
  },
]

/**
 * 12 Realistic Customers in Bengaluru with exact coordinates
 */
export const initialCustomers: CustomerRecord[] = [
  {
    id: 1,
    name: 'Ananya Nair',
    phone: '+91 98765 11223',
    location: '14 Palm Grove, Indiranagar',
    lat: 12.9716,
    lng: 77.5946,
    previousBookings: 8,
    preferredLanguage: 'en',
  },
  {
    id: 2,
    name: 'Vikram Rao',
    phone: '+91 98765 22345',
    location: '88 4th Block, Koramangala',
    lat: 12.9352,
    lng: 77.6245,
    previousBookings: 5,
    preferredLanguage: 'en',
  },
  {
    id: 3,
    name: 'Meera Shah',
    phone: '+91 98765 33456',
    location: '24 8th Cross, Malleshwaram',
    lat: 13.0031,
    lng: 77.5643,
    previousBookings: 11,
    preferredLanguage: 'hi',
  },
  {
    id: 4,
    name: 'Kavya Menon',
    phone: '+91 98765 44567',
    location: '45 11th Main, Jayanagar',
    lat: 12.9308,
    lng: 77.5838,
    previousBookings: 4,
    preferredLanguage: 'en',
  },
  {
    id: 5,
    name: 'Rohan Das',
    phone: '+91 98765 55678',
    location: '102 Prestige Palms, Whitefield',
    lat: 12.9698,
    lng: 77.75,
    previousBookings: 6,
    preferredLanguage: 'hi',
  },
  {
    id: 6,
    name: 'Sana Khan',
    phone: '+91 98765 66789',
    location: '7 Spencer Rd, Frazer Town',
    lat: 12.998,
    lng: 77.612,
    previousBookings: 9,
    preferredLanguage: 'hi',
  },
  {
    id: 7,
    name: 'Arjun Iyer',
    phone: '+91 98765 77890',
    location: '19 27th Main, HSR Layout Sector 2',
    lat: 12.912,
    lng: 77.644,
    previousBookings: 3,
    preferredLanguage: 'en',
  },
  {
    id: 8,
    name: 'Divya Patel',
    phone: '+91 98765 88901',
    location: '55 Vittal Mallya Rd, Central',
    lat: 12.9705,
    lng: 77.596,
    previousBookings: 14,
    preferredLanguage: 'hi',
  },
  {
    id: 9,
    name: 'Nikhil Jain',
    phone: '+91 98765 99012',
    location: '12 Bull Temple Rd, Basavanagudi',
    lat: 12.942,
    lng: 77.575,
    previousBookings: 2,
    preferredLanguage: 'hi',
  },
  {
    id: 10,
    name: 'Pooja Singh',
    phone: '+91 98765 00123',
    location: '34 Halasuru Lake Rd, Ulsoor',
    lat: 12.982,
    lng: 77.625,
    previousBookings: 7,
    preferredLanguage: 'hi',
  },
]

/**
 * 20 Specific Bookable Catalog Services
 */
export const catalogServices: CatalogService[] = [
  {
    serviceId: 'srv-plumb-01',
    category: 'Plumber',
    serviceName: 'Tap & Mixer Leakage Repair',
    description: 'Fix dripping faucets, mixer cartridges, and washer seal replacements.',
    basePrice: 280,
    estimatedDuration: '45 mins',
    priorityOptions: ['Standard', 'Same Day'],
    requiredSkills: ['Pipe Fitting', 'Washers'],
  },
  {
    serviceId: 'srv-plumb-02',
    category: 'Plumber',
    serviceName: 'Pipeline Clog & Drainage Clearing',
    description: 'Complete mechanical clearing of blocked kitchen or bathroom drainage pipes.',
    basePrice: 420,
    estimatedDuration: '60 mins',
    priorityOptions: ['Standard', 'Emergency', 'Same Day'],
    requiredSkills: ['Drain Clearing', 'Pressure Testing'],
  },
  {
    serviceId: 'srv-plumb-03',
    category: 'Plumber',
    serviceName: 'Overhead Water Tank Cleaning & Valve Check',
    description: 'Sediment flush, bacterial scrub, and float valve replacement.',
    basePrice: 650,
    estimatedDuration: '90 mins',
    priorityOptions: ['Standard', 'Same Day'],
    requiredSkills: ['Tank Sanitation', 'Float Valve'],
  },
  {
    serviceId: 'srv-elec-01',
    category: 'Electrician',
    serviceName: 'Switchboard & Socket Replacement',
    description: 'Replace burned or sparking sockets, modular switches, and earthing checks.',
    basePrice: 320,
    estimatedDuration: '45 mins',
    priorityOptions: ['Standard', 'Same Day'],
    requiredSkills: ['Circuit Wiring', 'Earthing'],
  },
  {
    serviceId: 'srv-elec-02',
    category: 'Electrician',
    serviceName: 'Ceiling Fan Installation & Regulator Fix',
    description: 'Safe ceiling mount, balance blade adjustment, and electronic speed controller fix.',
    basePrice: 380,
    estimatedDuration: '50 mins',
    priorityOptions: ['Standard', 'Same Day'],
    requiredSkills: ['Fan Mounting', 'Capacitor Testing'],
  },
  {
    serviceId: 'srv-elec-03',
    category: 'Electrician',
    serviceName: 'Full Home Wiring Safety Inspection',
    description: 'Digital thermal inspection of main DB, MCB trips, neutral leakage, and safety report.',
    basePrice: 750,
    estimatedDuration: '120 mins',
    priorityOptions: ['Standard'],
    requiredSkills: ['High Voltage Safety', 'MCB Diagnostics'],
  },
  {
    serviceId: 'srv-clean-01',
    category: 'Cleaner',
    serviceName: 'Deep Home Cleaning & Disinfection',
    description: 'Intense scrub of floors, kitchen counters, appliances exterior, and sanitization.',
    basePrice: 650,
    estimatedDuration: '150 mins',
    priorityOptions: ['Standard', 'Same Day'],
    requiredSkills: ['Sanitization', 'Eco-friendly Supplies'],
  },
  {
    serviceId: 'srv-clean-02',
    category: 'Cleaner',
    serviceName: 'Intense Bathroom Descaling & Polishing',
    description: 'Removal of hard water stains from tiles, glass partitions, and chrome faucets.',
    basePrice: 420,
    estimatedDuration: '60 mins',
    priorityOptions: ['Standard', 'Same Day'],
    requiredSkills: ['Descaling', 'Tile Polishing'],
  },
  {
    serviceId: 'srv-carp-01',
    category: 'Carpenter',
    serviceName: 'Door Latch, Hinge & Lock Repair',
    description: 'Fix squeaky or jammed doors, install godrej mortise locks, and adjust hinges.',
    basePrice: 380,
    estimatedDuration: '45 mins',
    priorityOptions: ['Standard', 'Emergency'],
    requiredSkills: ['Lock Installation', 'Hinge Tuning'],
  },
  {
    serviceId: 'srv-carp-02',
    category: 'Carpenter',
    serviceName: 'Furniture Assembly (IKEA / Modular)',
    description: 'Precision assembly of study desks, wardrobes, beds, and wall anchors.',
    basePrice: 550,
    estimatedDuration: '90 mins',
    priorityOptions: ['Standard', 'Same Day'],
    requiredSkills: ['Modular Furniture', 'Wall Anchors'],
  },
  {
    serviceId: 'srv-paint-01',
    category: 'Painter',
    serviceName: 'Interior Room Touch-up & Spot Painting',
    description: 'Putty patch repair, stain blocking primer, and dual coats of acrylic emulsion.',
    basePrice: 700,
    estimatedDuration: '180 mins',
    priorityOptions: ['Standard'],
    requiredSkills: ['Stain Blocking', 'Emulsion Coating'],
  },
  {
    serviceId: 'srv-ac-01',
    category: 'AC Technician',
    serviceName: 'Split AC Power Jet Deep Service',
    description: 'High pressure water jet coil cleaning, indoor filter flush, and gas pressure check.',
    basePrice: 499,
    estimatedDuration: '60 mins',
    priorityOptions: ['Standard', 'Same Day'],
    requiredSkills: ['Pressure Jet', 'Refrigerant Check'],
  },
  {
    serviceId: 'srv-ac-02',
    category: 'AC Technician',
    serviceName: 'AC Refrigerant Gas Leak Fix & Refill',
    description: 'Nitrogen leak test, copper brazing, vacuum evacuation, and R-32/R-410 gas refill.',
    basePrice: 1450,
    estimatedDuration: '90 mins',
    priorityOptions: ['Standard', 'Same Day'],
    requiredSkills: ['Brazing', 'Gas Recharging'],
  },
  {
    serviceId: 'srv-appl-01',
    category: 'Appliance Repair',
    serviceName: 'Washing Machine Drum & Motor Diagnostics',
    description: 'Fix spin errors, drainage pump noise, belt replacement, and PCB diagnosis.',
    basePrice: 380,
    estimatedDuration: '60 mins',
    priorityOptions: ['Standard', 'Same Day'],
    requiredSkills: ['Motor Diagnostics', 'Drain Pump'],
  },
  {
    serviceId: 'srv-appl-02',
    category: 'Appliance Repair',
    serviceName: 'Refrigerator Cooling & Defrost Repair',
    description: 'Thermostat replacement, relay repair, condenser cleaning, and cooling recovery.',
    basePrice: 420,
    estimatedDuration: '60 mins',
    priorityOptions: ['Standard', 'Emergency'],
    requiredSkills: ['Thermostat', 'Condenser'],
  },
  {
    serviceId: 'srv-care-01',
    category: 'Caregiver',
    serviceName: 'Elderly Day Care & Mobility Support (4 hrs)',
    description: 'Assistance with walking, medication reminders, companionship, and light nutrition.',
    basePrice: 550,
    estimatedDuration: '240 mins',
    priorityOptions: ['Standard', 'Same Day'],
    requiredSkills: ['Mobility Support', 'First Aid'],
  },
  {
    serviceId: 'srv-care-02',
    category: 'Caregiver',
    serviceName: 'Post-Surgery Patient Nursing Assistance',
    description: 'Wound dressing oversight, vital signs monitoring, and mobility recovery.',
    basePrice: 650,
    estimatedDuration: '180 mins',
    priorityOptions: ['Standard', 'Same Day'],
    requiredSkills: ['Post-Op Nursing', 'Vital Signs'],
  },
  {
    serviceId: 'srv-gard-01',
    category: 'Gardener',
    serviceName: 'Balcony & Terrace Garden Overhaul',
    description: 'Soil aerating, organic compost blending, seasonal repotting, and pest pruning.',
    basePrice: 480,
    estimatedDuration: '90 mins',
    priorityOptions: ['Standard', 'Same Day'],
    requiredSkills: ['Horticulture', 'Organic Compost'],
  },
  {
    serviceId: 'srv-driv-01',
    category: 'Driver',
    serviceName: 'City Errand & Medical Chauffeur (4 hrs)',
    description: 'Dedicated professional driver in your personal vehicle for city appointments.',
    basePrice: 550,
    estimatedDuration: '240 mins',
    priorityOptions: ['Standard', 'Same Day'],
    requiredSkills: ['City Navigation', 'Automatic/Manual'],
  },
  {
    serviceId: 'srv-driv-02',
    category: 'Driver',
    serviceName: 'Bengaluru Airport Round-Trip Driver',
    description: 'Safe highway transfer to/from Kempegowda International Airport (BLR).',
    basePrice: 650,
    estimatedDuration: '180 mins',
    priorityOptions: ['Standard', 'Same Day'],
    requiredSkills: ['Highway Driving', 'Airport Transfer'],
  },
]

/**
 * 32 Relational Connected Bookings spanning all states
 */
export const initialBookings: Booking[] = [
  {
    id: 1001,
    service: 'Deep Home Cleaning & Disinfection',
    serviceId: 'srv-clean-01',
    worker: 'Priya Sharma',
    workerId: 4,
    customerId: 1,
    customerName: 'Ananya Nair',
    workerLat: 12.975,
    workerLng: 77.589,
    customerLat: 12.9716,
    customerLng: 77.5946,
    date: 'Today · 10:00 AM',
    status: 'Accepted',
    amount: 650,
    etaMinutes: 12,
    address: '14 Palm Grove, Indiranagar',
    invoiceNumber: 'INV-2025-0101',
    paymentMethod: 'Co-op UPI Pay',
    workerEarnings: 488,
    coopFee: 130,
    communityFund: 32,
  },
  {
    id: 1002,
    service: 'Tap & Mixer Leakage Repair',
    serviceId: 'srv-plumb-01',
    worker: 'Ramesh Verma',
    workerId: 101,
    customerId: 1,
    customerName: 'Ananya Nair',
    workerLat: 12.9795,
    workerLng: 77.601,
    customerLat: 12.9716,
    customerLng: 77.5946,
    date: '10 Mar 2025',
    status: 'Completed',
    amount: 380,
    address: '14 Palm Grove, Indiranagar',
    invoiceNumber: 'INV-2025-0098',
    rating: 5,
    review: 'Fast leak fix and very honest quote. Highly recommended!',
    paymentMethod: 'Co-op Wallet',
    workerEarnings: 285,
    coopFee: 76,
    communityFund: 19,
  },
  {
    id: 1003,
    service: 'Washing Machine Drum & Motor Diagnostics',
    serviceId: 'srv-appl-01',
    worker: 'Neha Gupta',
    workerId: 8,
    customerId: 2,
    customerName: 'Vikram Rao',
    workerLat: 12.965,
    workerLng: 77.59,
    customerLat: 12.9352,
    customerLng: 77.6245,
    date: '28 Feb 2025',
    status: 'Completed',
    amount: 480,
    invoiceNumber: 'INV-2025-0082',
    rating: 5,
    review: 'Diagnosed motor issue immediately and replaced faulty belt.',
    workerEarnings: 360,
    coopFee: 96,
    communityFund: 24,
  },
  {
    id: 1004,
    service: 'Full Home Wiring Safety Inspection',
    serviceId: 'srv-elec-03',
    worker: 'Rajesh Kumar',
    workerId: 1,
    customerId: 4,
    customerName: 'Kavya Menon',
    workerLat: 12.978,
    workerLng: 77.604,
    customerLat: 12.9308,
    customerLng: 77.5838,
    date: '18 Mar 2025',
    status: 'Pending',
    amount: 750,
    etaMinutes: 25,
    address: '45 11th Main, Jayanagar',
    invoiceNumber: 'INV-2025-0104',
  },
  {
    id: 1005,
    service: 'Split AC Power Jet Deep Service',
    serviceId: 'srv-ac-01',
    worker: 'Farhan Akhtar',
    workerId: 114,
    customerId: 8,
    customerName: 'Divya Patel',
    workerLat: 12.973,
    workerLng: 77.602,
    customerLat: 12.9705,
    customerLng: 77.596,
    date: 'Yesterday · 3:30 PM',
    status: 'Completed',
    amount: 499,
    rating: 5,
    review: 'AC cooling restored to brand-new condition. Very professional cleaning.',
    invoiceNumber: 'INV-2025-0099',
    workerEarnings: 374,
    coopFee: 100,
    communityFund: 25,
  },
  {
    id: 1006,
    service: 'Elderly Day Care & Mobility Support',
    serviceId: 'srv-care-01',
    worker: 'Meenakshi Sundaram',
    workerId: 117,
    customerId: 3,
    customerName: 'Meera Shah',
    workerLat: 12.974,
    workerLng: 77.599,
    customerLat: 13.0031,
    customerLng: 77.5643,
    date: '11 Mar 2025',
    status: 'Completed',
    amount: 550,
    rating: 5,
    review: 'Took extraordinary care of my grandmother with utmost patience.',
    invoiceNumber: 'INV-2025-0095',
    workerEarnings: 412,
    coopFee: 110,
    communityFund: 28,
  },
  {
    id: 1007,
    service: 'Door Latch, Hinge & Lock Repair',
    serviceId: 'srv-carp-01',
    worker: 'Vijay Patil',
    workerId: 111,
    customerId: 6,
    customerName: 'Sana Khan',
    workerLat: 12.968,
    workerLng: 77.608,
    customerLat: 12.998,
    customerLng: 77.612,
    date: 'Today · 2:00 PM',
    status: 'In Progress',
    amount: 380,
    etaMinutes: 8,
    address: '7 Spencer Rd, Frazer Town',
    invoiceNumber: 'INV-2025-0105',
    workerEarnings: 285,
    coopFee: 76,
    communityFund: 19,
  },
  {
    id: 1008,
    service: 'Balcony & Terrace Garden Overhaul',
    serviceId: 'srv-gard-01',
    worker: 'Prakash Rao',
    workerId: 119,
    customerId: 7,
    customerName: 'Arjun Iyer',
    date: '05 Mar 2025',
    status: 'Completed',
    amount: 480,
    rating: 4,
    review: 'Plants repotted well and organic fertilizer was very good.',
    invoiceNumber: 'INV-2025-0089',
    workerEarnings: 360,
    coopFee: 96,
    communityFund: 24,
  },
  {
    id: 1009,
    service: 'Bengaluru Airport Round-Trip Driver',
    serviceId: 'srv-driv-02',
    worker: 'Sumit Hegde',
    workerId: 120,
    customerId: 10,
    customerName: 'Pooja Singh',
    date: '02 Mar 2025',
    status: 'Completed',
    amount: 650,
    rating: 5,
    review: 'Punctual 4 AM pickup for early morning flight.',
    invoiceNumber: 'INV-2025-0078',
    workerEarnings: 488,
    coopFee: 130,
    communityFund: 32,
  },
  {
    id: 1010,
    service: 'Interior Room Touch-up & Spot Painting',
    serviceId: 'srv-paint-01',
    worker: 'Arjun Patel',
    workerId: 5,
    customerId: 5,
    customerName: 'Rohan Das',
    date: '15 Feb 2025',
    status: 'Completed',
    amount: 700,
    rating: 4,
    invoiceNumber: 'INV-2025-0062',
    workerEarnings: 525,
    coopFee: 140,
    communityFund: 35,
  },
]

/**
 * Aggregated Cooperative Dashboard Statistics
 */
export const initialCoopStats: CoopStats = {
  totalWorkers: 38,
  verifiedWorkers: 36,
  activeJobs: 6,
  completedJobs: 142,
  pendingJobs: 3,
  workerUtilization: 82, // 82% active or assigned
  totalRequests: 151,
  revenue: 148200,
  workerEarnings: 111150, // 75% returned to workers
  averageRating: 4.82,
  topServices: [
    { name: 'Plumber', count: 48, percentage: 32 },
    { name: 'Cleaner', count: 36, percentage: 24 },
    { name: 'Electrician', count: 28, percentage: 19 },
    { name: 'AC Technician', count: 21, percentage: 14 },
    { name: 'Caregiver', count: 18, percentage: 11 },
  ],
  demandByArea: [
    { zone: 'Central (Indiranagar / MG Rd)', requests: 56, activeWorkers: 14 },
    { zone: 'South (Koramangala / Jayanagar)', requests: 42, activeWorkers: 10 },
    { zone: 'North (Malleshwaram / Frazer Town)', requests: 31, activeWorkers: 8 },
    { zone: 'East (Whitefield / Bellandur)', requests: 22, activeWorkers: 6 },
  ],
}

/**
 * 7-Day AI Synthetic Demand Forecast Data (clearly marked as Demo/Synthetic)
 */
export const initialForecast: DemandForecast[] = [
  {
    id: 'fc-1',
    date: '12 Mar (Tue)',
    dayOfWeek: 'Tuesday',
    serviceType: 'Plumber',
    zone: 'Central Zone',
    requests: 38,
    weather: 'Clear (31°C)',
    holiday: false,
    trendPercent: 12,
    predictionText: 'Steady morning residential maintenance demand.',
  },
  {
    id: 'fc-2',
    date: '13 Mar (Wed)',
    dayOfWeek: 'Wednesday',
    serviceType: 'Plumber',
    zone: 'Central Zone',
    requests: 54,
    weather: 'Cloudy (29°C)',
    holiday: false,
    trendPercent: 22,
    predictionText: 'Plumbing demand expected to increase by 22% tomorrow in Central Zone due to seasonal supply maintenance.',
  },
  {
    id: 'fc-3',
    date: '14 Mar (Thu)',
    dayOfWeek: 'Thursday',
    serviceType: 'Cleaner',
    zone: 'South Zone',
    requests: 44,
    weather: 'Sunny (32°C)',
    holiday: false,
    trendPercent: 8,
    predictionText: 'Mid-week domestic move-in deep cleaning requests rising.',
  },
  {
    id: 'fc-4',
    date: '15 Mar (Fri)',
    dayOfWeek: 'Friday',
    serviceType: 'Electrician',
    zone: 'North Zone',
    requests: 72,
    weather: 'Warm (33°C)',
    holiday: false,
    trendPercent: 18,
    predictionText: 'Pre-weekend safety audits and AC servicing preparation surge.',
  },
  {
    id: 'fc-5',
    date: '16 Mar (Sat)',
    dayOfWeek: 'Saturday',
    serviceType: 'All Trades',
    zone: 'City-wide',
    requests: 86,
    weather: 'Sunny (34°C)',
    holiday: true,
    trendPercent: 28,
    predictionText: 'Peak weekend household demand (+28%). Additional 12 open worker slots advised.',
  },
  {
    id: 'fc-6',
    date: '17 Mar (Sun)',
    dayOfWeek: 'Sunday',
    serviceType: 'All Trades',
    zone: 'City-wide',
    requests: 78,
    weather: 'Clear (33°C)',
    holiday: true,
    trendPercent: 24,
    predictionText: 'Sustained family weekend home repairs and driving appointments.',
  },
  {
    id: 'fc-7',
    date: '18 Mar (Mon)',
    dayOfWeek: 'Monday',
    serviceType: 'Driver & Caregiver',
    zone: 'Central Zone',
    requests: 46,
    weather: 'Clear (30°C)',
    holiday: false,
    trendPercent: 5,
    predictionText: 'Normal weekday commute and elderly healthcare assistance schedules.',
  },
]

/**
 * Worker Welfare Record for the logged-in demo worker (Ravi Kumar)
 */
export const demoWorkerWelfare: WorkerWelfare = {
  insuranceStatus: 'Active · Pradhan Mantri Jan Arogya & Co-op Shield (₹5,00,000)',
  trainingCompleted: 'Advanced Electrical Safety & Child-Safe Fixtures (Level 3)',
  certificationStatus: 'Certified Master Electrician (Govt. ITI Accredited)',
  leaveBalance: 4, // 4 paid emergency days available
  welfareEligibility: 'Tier 1 Prime Member (Eligible for zero-interest equipment loans)',
  grievanceStatus: '0 Pending · Clean community standing',
}

/**
 * Realistic Demo Notifications for both Customer and Worker roles
 */
export const initialNotifications: NotificationItem[] = [
  // Customer Notifications
  {
    id: 'notif-c-1',
    role: 'customer',
    title: 'Worker Accepted Booking',
    message: 'Priya Sharma accepted your Deep Home Cleaning booking for today.',
    time: '5 min ago',
    read: false,
    type: 'booking',
  },
  {
    id: 'notif-c-2',
    role: 'customer',
    title: 'Worker is En Route',
    message: 'Priya Sharma is 1.2 km away. Estimated arrival in ~12 mins.',
    time: '12 min ago',
    read: false,
    type: 'booking',
  },
  {
    id: 'notif-c-3',
    role: 'customer',
    title: 'Service Completed & Verified',
    message: 'Plumbing repair by Ramesh Verma completed. Tap rating to confirm.',
    time: 'Yesterday',
    read: true,
    type: 'booking',
  },
  {
    id: 'notif-c-4',
    role: 'customer',
    title: 'Payment Receipt Ready',
    message: 'Payment of ₹380 confirmed. Invoice INV-2025-0098 generated.',
    time: 'Yesterday',
    read: true,
    type: 'payment',
  },
  {
    id: 'notif-c-5',
    role: 'customer',
    title: 'Community Dividend Active',
    message: 'Your bookings contributed ₹19 to the neighborhood artisan welfare fund.',
    time: '3 days ago',
    read: true,
    type: 'welfare',
  },

  // Worker Notifications
  {
    id: 'notif-w-1',
    role: 'worker',
    title: 'New Nearby Job Available',
    message: 'Deep home cleaning requested 1.8 km away by Ananya Nair.',
    time: '2 min ago',
    read: false,
    type: 'booking',
  },
  {
    id: 'notif-w-2',
    role: 'worker',
    title: 'Booking Confirmed',
    message: 'Customer location and contact details have been unlocked.',
    time: '15 min ago',
    read: false,
    type: 'booking',
  },
  {
    id: 'notif-w-3',
    role: 'worker',
    title: 'Weekly Earnings Credited',
    message: '₹16,700 service earnings + ₹1,200 co-op dividend credited to bank.',
    time: 'Yesterday',
    read: true,
    type: 'payment',
  },
  {
    id: 'notif-w-4',
    role: 'worker',
    title: 'Annual Health Shield Active',
    message: 'Your health & emergency cover has been renewed through March 2026.',
    time: '2 days ago',
    read: true,
    type: 'welfare',
  },
  {
    id: 'notif-w-5',
    role: 'worker',
    title: 'Safety Certification Refresher',
    message: 'Complete the 30-min annual electrical safety module by 25 March.',
    time: '4 days ago',
    read: true,
    type: 'system',
  },
]
